# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://nbrahmani.github.io"

# Google tracking id
# google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Brahmani Nutakki"
title: "{ Brahmani Nutakki }"
description: "Personal Webpage of Brahmani Nutakki."
keywords: "brahmani, nutakki, personal"
favicon: "/img/favicon.ico"
################
# Header layout#
################
black-favicon: "/img/black-lab-glass.ico"
background-img: "intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "Hey there! I'm Brahmani...."
me-img: "/img/jetpacktocat.png"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "Nov 2023 - May 2024"
    description: "PhD in Computer Science @ [Saarland University, Germany](https://www.uni-saarland.de/start.html)"
  - image: "/img/timeline/spidertocat.png"
    date: "Nov 2023 - May 2024"
    description: "Research Fellow @ [Departmemt of Peace Operations, United Nations](https://peacekeeping.un.org/en/department-of-peace-operations)"
  - image: "/img/timeline/spidertocat.png"
    date: "2022"
    description: "Researcher in Robotics @ [University of Hyderabad, India](https://uohyd.ac.in)"
  - image: "/img/timeline/baracktocat.jpg"
    date: "2017 - 2022"
    description: "Integrated M.Tech, Computer Science @ [University of Hyderabad, India](https://uohyd.ac.in)"

# First image of the Timeline
timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "brahmani3110@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb:
#   "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional
#   engineering projects. In his spare time, John likes to eat cotton candy."
# author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/nbrahmani"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com/in/brahmani-nutakki"
  - icon: "bsky"
    url: "https://bsky.app/profile/brahmaninutakki.bsky.social"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  # Blog: "latest-post"§
  Research: "timeline"
  Contact: "contact"
# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml
# Pagination path
paginate_path: "blog/page:num/"
# Enable minification SASS
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-spaceship
